// app/layout.jsx (or layout.tsx)
import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Use className, not variable */}
      <body className={`${manrope.className} antialiased`}>
          {/* <Navbar /> */}
          {children}
      </body>
    </html>
  );
}
